[package]

name = "server"
version = "0.0.1"
authors = ["Chang Liu <cliu712@aucklanduni.ac.nz>"]

[dependencies]
redis = "*"
iron = "*"
cookie = "*"
bodyparser = "*"
router = "*"

[dependencies.urlencoded]
git = "file:///home/chang/src/rust/urlencoded"
